// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=127.0.0.1;initial catalog=MaterialCodeSelectionPlatform;user id=devuser;password=devpwd`
//     Include Views:          `True`

using MaterialCodeSelectionPlatform.Domain.Entities;
using Microsoft.Extensions.Logging;

namespace MaterialCodeSelectionPlatform.Data
{
    /// <summary>
    /// A Dao Impl for ProjectCatalogMap table.
    /// </summary>
	public partial class ProjectCatalogMapDaoImpl : EntityDaoBase<ProjectCatalogMap>, IProjectCatalogMapDao
	{
		public ProjectCatalogMapDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_ComponentType table.
    /// </summary>
	public partial class TempComponentTypeDaoImpl : EntityDaoBase<TempComponentType>, ITempComponentTypeDao
	{
		public TempComponentTypeDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_CommodityCode table.
    /// </summary>
	public partial class TempCommodityCodeDaoImpl : EntityDaoBase<TempCommodityCode>, ITempCommodityCodeDao
	{
		public TempCommodityCodeDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_PropertyValue table.
    /// </summary>
	public partial class TempPropertyValueDaoImpl : EntityDaoBase<TempPropertyValue>, ITempPropertyValueDao
	{
		public TempPropertyValueDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for CommodityCodeAttribute table.
    /// </summary>
	public partial class CommodityCodeAttributeDaoImpl : EntityDaoBase<CommodityCodeAttribute>, ICommodityCodeAttributeDao
	{
		public CommodityCodeAttributeDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Device table.
    /// </summary>
	public partial class DeviceDaoImpl : EntityDaoBase<Device>, IDeviceDao
	{
		public DeviceDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for MaterialTakeOff table.
    /// </summary>
	public partial class MaterialTakeOffDaoImpl : EntityDaoBase<MaterialTakeOff>, IMaterialTakeOffDao
	{
		public MaterialTakeOffDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Project table.
    /// </summary>
	public partial class ProjectDaoImpl : EntityDaoBase<Project>, IProjectDao
	{
		public ProjectDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for SynchroDetail table.
    /// </summary>
	public partial class SynchroDetailDaoImpl : EntityDaoBase<SynchroDetail>, ISynchroDetailDao
	{
		public SynchroDetailDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for SynchroRecord table.
    /// </summary>
	public partial class SynchroRecordDaoImpl : EntityDaoBase<SynchroRecord>, ISynchroRecordDao
	{
		public SynchroRecordDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for User table.
    /// </summary>
	public partial class UserDaoImpl : EntityDaoBase<User>, IUserDao
	{
		public UserDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for UserProjectMap table.
    /// </summary>
	public partial class UserProjectMapDaoImpl : EntityDaoBase<UserProjectMap>, IUserProjectMapDao
	{
		public UserProjectMapDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for MaterialTakeOffDetail table.
    /// </summary>
	public partial class MaterialTakeOffDetailDaoImpl : EntityDaoBase<MaterialTakeOffDetail>, IMaterialTakeOffDetailDao
	{
		public MaterialTakeOffDetailDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Catalog table.
    /// </summary>
	public partial class CatalogDaoImpl : EntityDaoBase<Catalog>, ICatalogDao
	{
		public CatalogDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for ComponentType table.
    /// </summary>
	public partial class ComponentTypeDaoImpl : EntityDaoBase<ComponentType>, IComponentTypeDao
	{
		public ComponentTypeDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_PartNumber table.
    /// </summary>
	public partial class TempPartNumberDaoImpl : EntityDaoBase<TempPartNumber>, ITempPartNumberDao
	{
		public TempPartNumberDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_Property table.
    /// </summary>
	public partial class TempPropertyDaoImpl : EntityDaoBase<TempProperty>, ITempPropertyDao
	{
		public TempPropertyDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for CommodityCode table.
    /// </summary>
	public partial class CommodityCodeDaoImpl : EntityDaoBase<CommodityCode>, ICommodityCodeDao
	{
		public CommodityCodeDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for PartNumber table.
    /// </summary>
	public partial class PartNumberDaoImpl : EntityDaoBase<PartNumber>, IPartNumberDao
	{
		public PartNumberDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

    /// <summary>
    /// A Dao Impl for Temp_CCPropertyValue table.
    /// </summary>
	public partial class TempCCPropertyValueDaoImpl : EntityDaoBase<TempCCPropertyValue>, ITempCCPropertyValueDao
	{
		public TempCCPropertyValueDaoImpl(ILoggerFactory loggerFactory):base(loggerFactory)  { }
	}

}
