// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: ``
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=127.0.0.1;initial catalog=CommodityCodeSelectionPlatform;user id=devuser;password=devpwd`
//     Include Views:          `True`

using System;
using Microsoft.Extensions.DependencyInjection;
using CommodityCodeSelectionPlatform.Domain.Entities;

namespace CommodityCodeSelectionPlatform.Service.Exentions.DependencyInjection
{
/// <summary>
    /// Service实例注入扩展
    /// </summary>
    public static class ServiceServiceExtension
    {
		/// <summary>
        /// 注入Service实例
        /// </summary>
        /// <param name="services"></param>
        public static void AddScopedService(this IServiceCollection services)
        {
			services.AddScoped<ITempComponentTypeService, TempComponentTypeServiceImpl>();
			services.AddScoped<ITempCommodityCodeService, TempCommodityCodeServiceImpl>();
			services.AddScoped<ITempPartNumberService, TempPartNumberServiceImpl>();
			services.AddScoped<ITempPartNumberAttributeService, TempPartNumberAttributeServiceImpl>();
			services.AddScoped<ITempPropertyService, TempPropertyServiceImpl>();
			services.AddScoped<ICatalogService, CatalogServiceImpl>();
			services.AddScoped<ICommodityCodeService, CommodityCodeServiceImpl>();
			services.AddScoped<ICommodityCodeAttributeService, CommodityCodeAttributeServiceImpl>();
			services.AddScoped<IComponentTypeService, ComponentTypeServiceImpl>();
			services.AddScoped<IDeviceService, DeviceServiceImpl>();
			services.AddScoped<IMaterialTakeOffService, MaterialTakeOffServiceImpl>();
			services.AddScoped<IMaterialTakeOffDetailService, MaterialTakeOffDetailServiceImpl>();
			services.AddScoped<IPartNumberService, PartNumberServiceImpl>();
			services.AddScoped<IProjectService, ProjectServiceImpl>();
			services.AddScoped<IProjectCatalogMapService, ProjectCatalogMapServiceImpl>();
			services.AddScoped<ISynchroDetailService, SynchroDetailServiceImpl>();
			services.AddScoped<ISynchroRecordService, SynchroRecordServiceImpl>();
			services.AddScoped<IUserService, UserServiceImpl>();
			services.AddScoped<IUserProjectMapService, UserProjectMapServiceImpl>();
		}
	}
}
